from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(647, 351)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        MainWindow.setMaximumSize(QSize(900, 406))
        icon = QIcon()
        icon.addFile(u":/Square44x44Logo.targetsize-72.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: rgb(45, 45, 45);")
        MainWindow.setIconSize(QSize(44, 44))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.anime = QLabel(self.centralwidget)
        self.anime.setObjectName(u"anime")
        self.anime.setGeometry(QRect(0, 2, 651, 51))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.anime.sizePolicy().hasHeightForWidth())
        self.anime.setSizePolicy(sizePolicy2)
        font = QFont()
        font.setFamily(u"Cascadia Code ExtraLight")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.anime.setFont(font)
        self.anime.setStyleSheet(u"background-color: rgb(35, 35, 35);\n"
"color: rgb(255, 255, 255);")
        self.anime.setTextFormat(Qt.AutoText)
        self.anime.setScaledContents(False)
        self.anime.setAlignment(Qt.AlignCenter)
        self.character = QLabel(self.centralwidget)
        self.character.setObjectName(u"character")
        self.character.setGeometry(QRect(0, 60, 641, 61))
        sizePolicy2.setHeightForWidth(self.character.sizePolicy().hasHeightForWidth())
        self.character.setSizePolicy(sizePolicy2)
        font1 = QFont()
        font1.setFamily(u"Cascadia Code Light")
        font1.setPointSize(15)
        font1.setBold(True)
        font1.setWeight(75)
        self.character.setFont(font1)
        self.character.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.character.setAlignment(Qt.AlignCenter)
        self.quote = QLabel(self.centralwidget)
        self.quote.setObjectName(u"quote")
        self.quote.setGeometry(QRect(10, 130, 621, 161))
        sizePolicy.setHeightForWidth(self.quote.sizePolicy().hasHeightForWidth())
        self.quote.setSizePolicy(sizePolicy)
        self.quote.setMinimumSize(QSize(0, 0))
        font2 = QFont()
        font2.setFamily(u"Calibri")
        font2.setPointSize(13)
        font2.setBold(False)
        font2.setWeight(50)
        self.quote.setFont(font2)
        self.quote.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.quote.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.quote.setWordWrap(True)
        self.button = QPushButton(self.centralwidget)
        self.button.setObjectName(u"button")
        self.button.setGeometry(QRect(260, 300, 121, 23))
        font3 = QFont()
        font3.setFamily(u"Cascadia Code")
        font3.setPointSize(9)
        font3.setBold(False)
        font3.setWeight(50)
        self.button.setFont(font3)
        self.button.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-image: url(:/buttonpic.png);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Anime Quotes", None))
        self.anime.setText(QCoreApplication.translate("MainWindow", u"Anime", None))
        self.character.setText(QCoreApplication.translate("MainWindow", u"Character", None))
        self.quote.setText(QCoreApplication.translate("MainWindow", u"Quote", None))
        self.button.setText(QCoreApplication.translate("MainWindow", u"Randomize Quote", None))
    # retranslateUi

